#!/usr/bin/env bash
#Bash script that display information about subdomains
domain=$1

if [ "$#" -eq 2 ]; then
    echo -n "The subdomain $2"
    dig "$2.$domain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print " is a " $4 " record and points to " $5}'
else
    dig "www.$domain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print "The subdomain www is a " $4 " record and points to " $5}'
    dig "lb-01.$domain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
    dig "web-01.$domain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print "The subdomain web-01 is a " $4 " record and points to " $5}'
    dig "web-02.$domain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print "The subdomain web-02 is a " $4 " record and points to " $5}'
fi