#!/usr/bin/env bash
# Install nginx on your web-01 server
apt-get -y update
apt-get -y install nginx
sudo chown -R $ubuntu:$ubuntu /var/www
sudo echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart