#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $ubuntu:$ubuntu /var/www
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start