#!/usr/bin/env bash
# configures a brand new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
hostname=$(cat /etc/hostname)
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx start