#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sed -i "\$ a\listen 1072-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\tserver 1401-web-01 34.73.220.28:80 check\n\tserver 1401-web-02 104.196.5.68:80 check" /etc/haproxy/haproxy.cfgsudo
sudo service haproxy start