#!/usr/bin/env bash
# This script displays Holberton School 10 times for the 9th iteration print Hi4
i=1
while [ "$i" -le "10" ]
do echo "Holberton School"
  if [ "$i" -eq "9" ]
  then
    echo "Hi"
    fi
  ((i++))
done
