#!/usr/bin/env bash
# Displays bad luck for the 4th loop and good luck for the 8th loop and Holberton School for the others
i=0
while [ $i -lt 10 ]
do
  if [ $i -eq 3 ]
  then
    echo "bad luck"
  elif [ $i -eq 7 ]
  then
    echo "good luck"
  else
    echo "Holberton School"
  fi
  ((i++))
done
