#!/usr/bin/env bash
# run nginx as nginx and listen on port 8080
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
