#!/usr/bin/env bash
# run nginx as nginx and listen on port 8080
pkill -f apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start